#开发环境配置
server:
  port: 8765

#Spring 配置
spring:
  profiles:
    active: local

#token配置
token:
  #令牌自定义标识
  header: Authorization
  #令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  #令牌有效期（默认30分钟）
  expireTime: 30

#Mybatis plus配置
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath:/mapper/*.xml
